@startuml
class Main<<(/,white)>>{
        勤怠入力api
        勤怠集計api
        int main(String)
    }

package "API" #DDDDDD{
    Main o.. 勤怠入力api
    Main o.. 勤怠集計api

    class 勤怠入力api<<(A,white)>>{
        勤怠入力service
        void 勤怠入力(勤務日付,始業時刻,退社時刻)
    }
    class 勤怠集計api<<(A,white)>>{
        勤怠集計service
        String 勤怠集計取得(年月)
    }
}

package "service" #DDDDDD{
    勤怠入力api o.. 勤怠入力service
    勤怠集計api o.. 勤怠集計service

    class 勤怠集計service<<(S,white)>>{
        勤怠集計リポジトリ
        勤怠集計 集計(年月)
    }
    class 勤怠入力service<<(S,white)>>{
        勤怠入力リポジトリ
        void 勤怠入力(勤務日付,出社時刻,退社時刻)
    }
}



package "Domain" #DDDDDD{
            class 勤怠入力リポジトリ<<(R,yellow)Repository>>{
                   void 勤怠登録(勤務履歴)
            }
            class 勤怠<< (V,lightblue) ValueObject >>{
                勤務履歴List
                就業規則
                勤怠 create (勤務履歴List)
                勤怠集計 勤務時間算出()
            }
            class 勤務履歴List<<(V,lightblue) ValueObject>>{
                 List<勤務履歴>
            }
            class 就業規則<< (V,lightblue) ValueObject >> {
                始業時刻
                終業時刻
                休憩時間List
            }

            class 始業時刻<< (V,lightblue) ValueObject >>{
                LocalTime
                boolean is遅刻(勤務履歴)
            }
            class 終業時刻<< (V,lightblue) ValueObject >>{
                 LocalTime
                 boolean is早退(勤務履歴)
             }
             class 休憩時間リスト<< (V,lightblue) ValueObject >>{
                 List<休憩時間>
                 時間 休憩時間合計()
             }
            class 休憩時間<< (V,lightblue) ValueObject >>{
                休憩開始時刻
                休憩終了時刻
                時間 休憩計算(勤務履歴)
            }
            class 休憩開始時刻<< (V,lightblue) ValueObject >>{
                LocalTime
            }
            class 休憩終了時刻<< (V,lightblue) ValueObject >>{
                LocalTime
            }
            class 勤怠集計リポジトリ <<(R,yellow) Repository>>{
                勤務履歴List 勤怠履歴取得(年月)
            }
            class 勤怠集計<< (V,lightblue) ValueObject >>{
            勤務時間
            残業時間
            }
            class 勤務時間<< (V,lightblue) ValueObject >>{
            }
            class 残業時間<< (V,lightblue) ValueObject >>{
            }

            勤怠入力service ..> 勤怠入力リポジトリ

            勤怠 o.. 就業規則
            勤怠 o.. 勤務履歴List
            勤怠 ..> 勤怠集計
            勤怠集計 o.. 勤務時間
            勤怠集計 o.. 残業時間
            勤怠集計リポジトリ ..> 勤怠
            就業規則  o--  休憩時間リスト
            就業規則  o--  終業時刻
            就業規則  o--  始業時刻
            休憩時間リスト "1" o-- "n" 休憩時間
            休憩時間  o-- 休憩開始時刻
            休憩時間  o-- 休憩終了時刻
            勤怠集計service ..> 勤怠集計リポジトリ

            package "勤怠登録" #white{
                class 勤務履歴<<(E,red)Entity>>{
                    勤務日付
                    出社時刻
                    退社時刻
                    勤務履歴 create(勤務日付,出社時刻,退社時刻)
                }
                class 勤務日付<< (V,lightblue) ValueObject >>{
                    LocalDate
                }
                class 出社時刻<< (V,lightblue) ValueObject >>{
                    LocalTime
                }
                class 退社時刻<< (V,lightblue) ValueObject >>{
                    LocalTime
                }
                勤務履歴List "1" o.. "n" 勤務履歴

                勤怠入力service ..> 勤務履歴
                勤務履歴  o--  勤務日付
                勤務履歴  o--  出社時刻
                勤務履歴  o--  退社時刻

            }



}
package "Datasource" #white{
    勤怠入力リポジトリ <|.... 勤怠入力リポジトリDb
    勤怠集計リポジトリ <|.... 勤怠集計リポジトリDb

    class 勤怠入力リポジトリDb<<(D,yellow)datasource>>{
        勤怠入力Mapper
        void 勤怠書込(勤務履歴)
    }
    note bottom:更新のロジックは\nここに持たせる？
    class 勤怠集計リポジトリDb<<(D,yellow)datasource>>{
        勤怠集計Mapper
        勤怠履歴List 勤怠履歴取得(年月)

    }
    package "QueryMapper" #white{
        class 勤怠入力mapper<<(D,yellow)Mapper>>{
            void 勤怠書込(勤務履歴)
            boolean 書込済み？()
            void 勤怠更新()
        }
        class 勤怠集計mapper<<(D,yellow)Mapper>>{
           勤怠履歴List 勤怠履歴取得(年月)
        }
        勤怠入力リポジトリDb ..> 勤怠入力mapper
        勤怠集計リポジトリDb ..> 勤怠集計mapper
    }
}

@enduml